チャレンジ課題
kmhm212/score_input pull request #1
Opened 2021-03-13 00:36 UTC by kmhm212

2021-03-13 00:41 UTC, kmhm212 commented
PHPの方はそれっぽく書けたものの
cssがなぜか紐付いて動いてくれず「？？？」状態…。

2021-03-13 13:10 UTC, kazu-taka requested changes
@kmhm212 
いくつかコメントしたので確認お願いします🙏

2021-03-13 13:10 UTC, kazu-taka commented on input.php
> +        if (empty ($points[$su]) && $points[$su] != "0") {
@kmhm212 
フォームで0〜100、もしくは""しか入力されないようになっているので、もっとシンプルに判定してOKです👍

2021-03-13 13:10 UTC, kazu-taka commented on input.php
> +    ];
@kmhm212 
ここで2つの連想配列を作成するよりは、1つにまとめて連想配列の入れ子のようにした方が管理しやすいと思うので、1つにまとめてみて下さい👍

2021-03-13 13:10 UTC, kazu-taka commented on input.php
> +                        <?= $err_message ?>
@kmhm212 
HTML内でPHPの変数の値を出力する時は、エスケープ(htmlspecialchars)した方がよいので、エスケープするようにお願いします！！
他の部分も修正お願いします！！
https://teratail.com/questions/212107#reply-312435

2021-03-16 11:31 UTC, kazu-taka requested changes
@kmhm212 
コメントしたので確認お願いします🙏

2021-03-16 11:31 UTC, kazu-taka commented on input.php
> +    }
@kmhm212 
今の処理だと以下の連想配列が処理の途中から

```php
[
    'name' => '名前',
    'japanese' => '国語の点数',
    'mathematics' => '数学の点数',
    'science' => '理科の点数',
    'social_studies' => '社会の点数',
    'english' => '英語の点数',
];
```

このようになり、セットされている値の意味合いが変わってきてしまうので、japaneseの中にタイトルと点数の2つを保持するようにした方がいいと思います👍
そうなると書く文字としては多くなりますが、後から見た時に外の人が理解しやすくなると思います✨

```php
[
    'name' => 'テスト太郎',
    'japanese' => '90',
    'mathematics' => '30',
    'science' => '40',
    'social_studies' => '100',
    'english' => '50',
];
```

2021-03-16 11:31 UTC, kazu-taka commented on input.php
> +        if (empty($topics[$tpc]) && $topics[$tpc] == "") {
@kmhm212 
ここはフォームで0〜100、もしくは""しか入力されないようになっています！
0〜100はOKなので""だったらNGと判定するだけでOKです👍

2021-03-17 04:00 UTC, kazu-taka requested changes
@kmhm212 
もし納得頂けるのであれば修正お願いします😊

2021-03-17 04:00 UTC, kazu-taka commented on input.php
> +];
@kmhm212 
これでも問題ではないですが、
国語の点数を処理内で扱う場面があった場合、他の人がコードを見た時に

- `$topics['point'][1]`: 現状のコード
- `$topics['japanese']['point']`:  別のコード

のどちらが国語の点数を扱っているか判断しやすいかという基準でコードを書いた方が良いです✨

2021-03-19 00:28 UTC, kazu-taka reviewed
@kmhm212 
コードがとても綺麗で見やすいです😊
exitだけ追加したらマージしてOKです👍

2021-03-19 00:28 UTC, kazu-taka commented on input.php
> +];
@kmhm212 
連想配列にしたことにより、以降の処理が分かりやすくなったと思います👍

2021-03-19 00:28 UTC, kazu-taka commented on input.php
> +        header("Location: result.php");
@kmhm212 
講義で説明漏れてましたが、header関数の直後はexit関数を使用して処理を中断するようにして下さい🙏
https://github.com/elites-team/23rd-century-4th/blob/master/doc/06_php/study01/07.md#header%E9%96%A2%E6%95%B0

2021-03-20 02:04 UTC, merged